site:
  title: SEMIC
  start_page: ROOT::index.adoc

antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
    snippet_length: 170
    languages: [en]

content:
  sources:
#    - url: .
    - url: https://github.com/SEMICeu/style-guide
      branches: [ main ]
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
